<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es-ES" xml:lang="es-ES"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Javier Rodríguez_Barrios y Kenedith Méndez">
<meta name="dcterms.date" content="2023-05-02">

<title>Taller 6. Visualización de Poblaciones</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Taller6.poblaciones_files/libs/clipboard/clipboard.min.js"></script>
<script src="Taller6.poblaciones_files/libs/quarto-html/quarto.js"></script>
<script src="Taller6.poblaciones_files/libs/quarto-html/popper.min.js"></script>
<script src="Taller6.poblaciones_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Taller6.poblaciones_files/libs/quarto-html/anchor.min.js"></script>
<link href="Taller6.poblaciones_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Taller6.poblaciones_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Taller6.poblaciones_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Taller6.poblaciones_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Taller6.poblaciones_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción</a></li>
  <li><a href="#objetivo-de-la-actividad" id="toc-objetivo-de-la-actividad" class="nav-link" data-scroll-target="#objetivo-de-la-actividad">Objetivo de la actividad</a>
  <ul>
  <li><a href="#modelos-de-crecimiento-exponencial" id="toc-modelos-de-crecimiento-exponencial" class="nav-link" data-scroll-target="#modelos-de-crecimiento-exponencial"><b style="color:#d95f02;"> Modelos de crecimiento exponencial </b></a></li>
  <li><a href="#modelos-de-crecimiento-logístico" id="toc-modelos-de-crecimiento-logístico" class="nav-link" data-scroll-target="#modelos-de-crecimiento-logístico"><b style="color:#d95f02;"> Modelos de crecimiento logístico </b></a></li>
  <li><a href="#librerías-requeridas" id="toc-librerías-requeridas" class="nav-link" data-scroll-target="#librerías-requeridas"><b style="color:#1f78b4;"> Librerías requeridas </b></a></li>
  <li><a href="#respuestas-al-cuestionario" id="toc-respuestas-al-cuestionario" class="nav-link" data-scroll-target="#respuestas-al-cuestionario"><b style="color:#1f78b4;"> Respuestas al cuestionario </b></a></li>
  <li><a href="#modelos-de-crecimiento-exponencial-1" id="toc-modelos-de-crecimiento-exponencial-1" class="nav-link" data-scroll-target="#modelos-de-crecimiento-exponencial-1"><b style="color:#d95f02;"> Modelos de crecimiento exponencial </b></a></li>
  <li><a href="#modelos-de-crecimiento-logístico-1" id="toc-modelos-de-crecimiento-logístico-1" class="nav-link" data-scroll-target="#modelos-de-crecimiento-logístico-1"><b style="color:#d95f02;"> Modelos de crecimiento logístico </b></a></li>
  </ul></li>
  <li><a href="#cuestionario-para-resolver-en-casa" id="toc-cuestionario-para-resolver-en-casa" class="nav-link" data-scroll-target="#cuestionario-para-resolver-en-casa">Cuestionario para resolver en casa</a>
  <ul>
  <li><a href="#modelos-de-crecimiento-exponencial-2" id="toc-modelos-de-crecimiento-exponencial-2" class="nav-link" data-scroll-target="#modelos-de-crecimiento-exponencial-2"><b style="color:#d95f02;"> Modelos de crecimiento Exponencial </b></a></li>
  <li><a href="#modelos-de-crecimiento-logístico-2" id="toc-modelos-de-crecimiento-logístico-2" class="nav-link" data-scroll-target="#modelos-de-crecimiento-logístico-2"><b style="color:#d95f02;"> Modelos de crecimiento Logístico </b></a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Taller 6. Visualización de Poblaciones</h1>
<p class="subtitle lead">Datos de …</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Javier Rodríguez_Barrios y Kenedith Méndez </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 2, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/pinguino.jpg" class="img-fluid figure-img" style="width:60.0%"></p>
<p></p><figcaption class="figure-caption"><n style="color:#1f78b4;"> Imágen tomada de <a href="https://www.pexels.com/es-es/foto/naturaleza-pajaro-animal-mono-4147986/">Foto de Vladimir Blyufer</a> </n></figcaption><p></p>
</figure>
</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b><section id="introducción" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p><em>Pendiente de documentar …</em></p>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="objetivo-de-la-actividad" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="objetivo-de-la-actividad">Objetivo de la actividad</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Dar respuesa con procedimientos de visualización gráfica en R, a las siguientes preguntas, asociadas a modelos exponenciales y logísticos de crecimiento poblacional.</p>
<section id="modelos-de-crecimiento-exponencial" class="level3">
<h3 class="anchored" data-anchor-id="modelos-de-crecimiento-exponencial"><b style="color:#d95f02;"> Modelos de crecimiento exponencial </b></h3>
<ol type="1">
<li><p>Una población biológica crece a una tasa anual del 6%. Si la población actual es de 5000, ¿cuál será en 7 años?</p></li>
<li><p>Una población de aves crece a un ritmo anual del 5%. Si la población actual es de 2000, ¿cuántos años se tardará para que vuelvan a doblar? Redondea tu respuesta a la centésima más cercana.</p></li>
<li><p>Una población de hormigas presenta una tasa de disminución anual del 7,2%. ¿Cuántos años le tomará a esta población de 227 gramos para llegar a 93 gramos de biomasa?</p></li>
<li><p>Supongamos que la población de peces marinos crece a una tasa anual del 7%. Si la población actual es de 8000 individuos, ¿cuántos años se tardará para que llegue a 18000?</p></li>
</ol>
</section>
<section id="modelos-de-crecimiento-logístico" class="level3">
<h3 class="anchored" data-anchor-id="modelos-de-crecimiento-logístico"><b style="color:#d95f02;"> Modelos de crecimiento logístico </b></h3>
<ol start="15" type="1">
<li><p>Suponga que una población de mariposas crece de acuerdo a la ecuación logística. Si la capacidad de carga es de 500 mariposas y r= 0.1 ind/ind.més ¿cuál es la tasa de crecimiento para la población?</p></li>
<li><p>Un biólogo pesquero quiere maximizar la producción de trucha manteniendo la población de truchas en exactamente 500 individuos (el biólogo asume que este es el tamaño conducente a la máxima tasa de crecimiento poblacional y que su población crece en forma logística). Prediga la tasa de crecimiento poblacional inicial al adicionar a la población 600 peces y explique su significado. Asuma que r para las truchas es de 0.005 individuos/individuo.día</p></li>
<li><p>Se estudia una población de tortugas denso-dependiente que tienen las siguientes relaciones para las tasas de nacimiento (b’) y mortalidad (d’) en función del tamaño poblacional, N:</p>
<p>b’= 0.10 + 0.03N – 0.0005N2</p>
<p>d’ = 0.20 + 0.01N</p></li>
</ol>
<p>Grafique estas funciones en el mismo gráfico y discuta la dinámica poblacional de la tortuga. ¿En qué difiere este modelo del modelo simple logístico con funciones lineales de nacimientos y muertes?</p>
<ol start="18" type="1">
<li>Averiguar por los siguientes conceptos ecológicos y mencionar un ejemplo de cada uno: (1) Autoadelgazamiento (selfthining), modelo de competencia scramble, y competencia context.</li>
</ol>
</section>
<section id="librerías-requeridas" class="level3">
<h3 class="anchored" data-anchor-id="librerías-requeridas"><b style="color:#1f78b4;"> Librerías requeridas </b></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="respuestas-al-cuestionario" class="level3">
<h3 class="anchored" data-anchor-id="respuestas-al-cuestionario"><b style="color:#1f78b4;"> Respuestas al cuestionario </b></h3>
</section>
<section id="modelos-de-crecimiento-exponencial-1" class="level3">
<h3 class="anchored" data-anchor-id="modelos-de-crecimiento-exponencial-1"><b style="color:#d95f02;"> Modelos de crecimiento exponencial </b></h3>
<p><img src="https://t3.ftcdn.net/jpg/04/29/87/06/240_F_429870613_wicblqS40tgfWXveGpN6yhttW1rUTNZG.jpg" width="40%"></p>
<p><b style="color:#d95f02;"> Pregunta 1. Población </b></p>
<p><img src="https://media.istockphoto.com/id/861123250/es/foto/multitud-de-gente-en-la-calle.jpg?s=612x612&amp;w=0&amp;k=20&amp;c=VwdbSQGrhs3mPqUH0yVhvbSylepXb-nMpFKANYcOjcE=" width="40%"></p>
<p>Una población biológica crece a una tasa anual del 6%. Si la población actual es de 5000:</p>
<ol type="1">
<li><p>¿Cuál será en 7 años?</p></li>
<li><p>Graficar la proyección de esta población en 10 periodos de tiempo.</p></li>
</ol>
<p><strong>R./</strong> Primero hay que utilizar la fórmula para el crecimiento exponencial de una población biológica:</p>
<p><b style="color:#1f78b4;"> Nt = No * e^(r*t) </b></p>
<p><em>Donde</em>:</p>
<p><strong>Nt</strong>= densidad de la población después de un tiempo t</p>
<p><strong>No</strong>= densidad inicial de la población (en el tiempo 0)</p>
<p><strong>r</strong>= tasa de crecimiento intrinsico o instantaneo.</p>
<p><strong>t</strong>= tiempo transcurrido (expresado en años)</p>
<p>En este caso, se tiene que:</p>
<p><strong>No</strong>= 5000 individuos</p>
<p><strong>r</strong>= 0.06 indv./indv.*t (6% expresado como un decimal)</p>
<p><strong>t</strong>= 7 años</p>
<p><em>Preguntas a resolver:</em></p>
<ol type="1">
<li><p><strong>N7</strong>= ?</p></li>
<li><p>Proyección exponencial en 10 periodos de tiempo</p></li>
</ol>
<p><em>Procedimiento</em></p>
<ol type="1">
<li>Calculo de la densidad de la población después de 7 años.</li>
</ol>
<ul>
<li>Función asignada como <code>población</code> (<code>Nt</code>) la cual permite estimar el crecimiento de la población Nt, basado en la densidad inicial <code>No</code>, en la tasa de crecimiento intrisico o instantánea <code>r</code> en periodos de tiempo especificos <code>t</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 1: Función para el crecimiento exponencial</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>Nt <span class="ot">&lt;-</span> <span class="cf">function</span>(No, r, t) {</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  No <span class="sc">*</span> <span class="fu">exp</span>(r <span class="sc">*</span> t)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>Nt</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function(No, r, t) {
  No * exp(r * t)
}</code></pre>
</div>
</div>
<p>La función anterior se puede reemplazar por la siguiente más sencilla, así:</p>
<p>Nt &lt;- No * exp(r * t)</p>
<ul>
<li>Cálculo del tamaño de la población en 7 periodos de tiempo <code>N7</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimación la densidad de la población (Nt) después de 7 años (N7)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>N7 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">Nt</span>(<span class="at">No =</span> <span class="dv">5000</span>, <span class="at">r =</span> <span class="fl">0.06</span>, <span class="at">t =</span> <span class="dv">7</span>))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>N7</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7610</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Figura del modelo de proyección de la población en 10 periodos de tiempo.</li>
</ol>
<ul>
<li>Base de datos o data frame <code>datos</code>, en 10 periodos de tiempo, para posteriormente realizar la figura del modelo exponencial en ggplot.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data frame con los valores de población para varios tiempos</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">10</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Nt =</span> <span class="fu">Nt</span>(<span class="at">No =</span> <span class="dv">5000</span>, <span class="at">r =</span> <span class="fl">0.06</span>, <span class="at">t =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">10</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(datos,<span class="dv">0</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    t   Nt
1   0 5000
2   1 5309
3   2 5637
4   3 5986
5   4 6356
6   5 6749
7   6 7167
8   7 7610
9   8 8080
10  9 8580
11 10 9111</code></pre>
</div>
</div>
<ul>
<li>Figura del modelo de proyección de la población en 10 periodos de tiempo.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafica de la evolución de la población</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> Nt)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafica de la evolución de la población</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> Nt)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">7</span>, <span class="at">y =</span> N7), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">7</span>, <span class="at">y =</span> N7, <span class="at">label =</span> N7), <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Tiempo (años)"</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Densidad Poblacional (N)"</span>) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Crecimiento Exponencial"</span>) <span class="sc">+</span> </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En la figura resultante, se observa cómo la población crece exponencialmente a lo largo de los 10 periodos de tiempo, y cómo después de 7 periodos, la población alcanza un valor de aproximadamente 7,764 individuos.</p>
<p><b style="color:#d95f02;"> Pregunta 2. Población de aves </b></p>
<p><img src="https://images.pexels.com/photos/13779401/pexels-photo-13779401.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=1260&amp;h=750&amp;dpr=1" width="40%"></p>
<p>Una población de aves crece a un ritmo anual del 5%. Si la población actual es de 2000,</p>
<ol type="1">
<li><p>¿cuántos años se tardará para que vuelvan a doblar? Redondea tu respuesta a la centésima más cercana.</p></li>
<li><p>Graficar la proyección de esta población en 20 periodos de tiempo.</p></li>
</ol>
<p><strong>R./</strong> Se requiere utilizar la fórmula para el crecimiento exponencial:</p>
<p><b style="color:#1f78b4;"> Nt = No * e^(r*t) </b></p>
<p><em>Ver los elementos de esta ecuación en el ejercicio anterior.</em></p>
<p>En este caso, se tiene que:</p>
<p><strong>No</strong>= 2000 individuos</p>
<p><strong>r</strong>= 0.05 indv./indv.*t (aumento del 5%)</p>
<p><strong>t</strong>= 7 años</p>
<p><em>Preguntas a resolver:</em></p>
<ol type="1">
<li><p><strong>tdoble</strong>= ?</p></li>
<li><p>Proyección exponencial en 10 periodos de tiempo</p></li>
</ol>
<p><em>Procedimiento</em></p>
<ol type="1">
<li>En este caso, se requiere saber cuántos años tardará la población en duplicarse. Para hacer esto, tenemos que:</li>
</ol>
<p><b style="color:#1f78b4;"> tdoble = ln(2) / r </b></p>
<p>En este caso:</p>
<p>No = 2000 r = 0.05 indv./indv.*t (5%)</p>
<ul>
<li>Función asignada como <code>población</code> (<code>Nt</code>) la cual permite estimar el crecimiento de la población Nt, basado en la densidad inicial <code>No</code>, en la tasa de crecimiento intrisico o instantánea <code>r</code> en periodos de tiempo especificos <code>t</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos la función para el crecimiento exponencial</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Nt <span class="ot">&lt;-</span> <span class="cf">function</span>(No, r, t) {</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  No <span class="sc">*</span> <span class="fu">exp</span>(r <span class="sc">*</span> t)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>Nt</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function(No, r, t) {
  No * exp(r * t)
}</code></pre>
</div>
</div>
<ul>
<li>Cálculo del tiempo de duplicación de la población <code>tdoble</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tiempo que tardará la población en duplicarse redondeado a dos decimales</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>tdoble <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">log</span>(<span class="dv">2</span>) <span class="sc">/</span> <span class="fl">0.05</span>, <span class="dv">2</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>tdoble</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.86</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Figura de la proyección poblacional en 20 periodos de tiempo o 20 años.</li>
</ol>
<ul>
<li>Base de datos o data frame <code>datos</code>, en 20 periodos de tiempo, para posteriormente realizar la figura del modelo exponencial en ggplot</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos un data frame con los valores de población para varios tiempos</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Nt =</span> <span class="fu">round</span>(<span class="fu">Nt</span>(<span class="at">No =</span> <span class="dv">2000</span>, <span class="at">r =</span> <span class="fl">0.05</span>, <span class="at">t =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>)))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  t   Nt
1 0 2000
2 1 2103
3 2 2210
4 3 2324
5 4 2443
6 5 2568</code></pre>
</div>
</div>
<ul>
<li>Figura del modelo de proyección de la población en 20 periodos de tiempo.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficamos la evolución de la población</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> Nt)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> tdoble, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">x =</span> tdoble <span class="sc">+</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="fu">max</span>(datos<span class="sc">$</span>Nt) <span class="sc">/</span> <span class="dv">2</span>, </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"Duplicación</span><span class="sc">\n</span><span class="st">en"</span>, tdoble, <span class="st">"años"</span>),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Tiempo (años)"</span>) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Población (N)"</span>) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Crecimiento exponencial de la población de aves"</span>) <span class="sc">+</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En la figura, se observa cómo la población crece exponencialmente a lo largo del tiempo, y cómo la línea vertical roja indica el momento en que la población se duplica. El tiempo que tardará la población en duplicarse es de aproximadamente 13.86 años.</p>
<p><b style="color:#d95f02;"> Pregunta 3. Población de Hormigas </b></p>
<p><img src="https://images.pexels.com/photos/3482985/pexels-photo-3482985.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=300" width="40%"></p>
<p>Una población de hormigas presenta una tasa de disminución anual del 7,2%.</p>
<ol type="1">
<li><p>¿Cuántos años le tomará a esta población de 227 gramos para llegar a 93 gramos de biomasa?</p></li>
<li><p>Graficar la proyección de esta población en 20 periodos de tiempo.</p></li>
</ol>
<p><strong>R./</strong> Se requiere utilizar la fórmula para el crecimiento exponencial:</p>
<p><b style="color:#1f78b4;"> Nt = No * e^(r*t) </b></p>
<p><em>Ver los elementos de esta ecuación en el ejercicio anterior.</em></p>
<p>En este caso, se tiene que:</p>
<p><strong>No</strong>= 227 gramos</p>
<p><strong>Nt</strong>= 93 gramos</p>
<p><strong>t</strong>= ?</p>
<p><strong>r</strong>= -0.072 indv./indv.*t (disminución del 7.2%)</p>
<p><em>Preguntas a resolver:</em></p>
<ol type="1">
<li><p><strong>t</strong>= ?</p></li>
<li><p>Proyección exponencial en 10 periodos de tiempo</p></li>
</ol>
<p><em>Procedimiento</em></p>
<ol type="1">
<li>En este caso, si: <b style="color:#1f78b4;"> Nt = No * e^(r*t) </b>.</li>
</ol>
<p>De acuerdo a diferentes despejes logarítmicos:</p>
<p><b style="color:#1f78b4;"> t= [ln(Nt/No)]/[r * ln(e)] </b></p>
<p><strong>t</strong>= [ln(93/227)]/[-0.072 * 1]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos la función para la disminución exponencial</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>biomasa <span class="ot">&lt;-</span> <span class="cf">function</span>(No, r, t) {</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  No <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>r <span class="sc">*</span> t)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>biomasa</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function(No, r, t) {
  No * exp(-r * t)
}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>t <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">log</span>(<span class="dv">93</span><span class="sc">/</span><span class="dv">227</span>)<span class="sc">/</span>(<span class="sc">-</span><span class="fl">0.072</span> <span class="sc">*</span> <span class="dv">1</span>), <span class="dv">2</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>t</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.39</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Figura de la proyección poblacional en 20 periodos de tiempo o 20 años.</li>
</ol>
<ul>
<li>Base de datos o data frame <code>datos</code>, en 20 periodos de tiempo, para posteriormente realizar la figura del modelo exponencial en ggplot</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos un data frame con los valores de población para varios tiempos</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">biom =</span> <span class="fu">biomasa</span>(<span class="at">No =</span> <span class="dv">227</span>, <span class="at">r =</span> <span class="fl">0.072</span>, <span class="at">t =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  t     biom
1 0 227.0000
2 1 211.2305
3 2 196.5565
4 3 182.9019
5 4 170.1959
6 5 158.3725</code></pre>
</div>
</div>
<ul>
<li>Figura del modelo de proyección de la población en 20 periodos de tiempo.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficamos la evolución de la población</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> biom)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">93</span>, </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">x =</span> <span class="fu">max</span>(datos<span class="sc">$</span>t) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="dv">100</span>, </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"Llegada</span><span class="sc">\n</span><span class="st">a 93 g</span><span class="sc">\n</span><span class="st">en"</span>, t, <span class="st">"años"</span>),</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Tiempo (años)"</span>) <span class="sc">+</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Biomasa (g)"</span>) <span class="sc">+</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Disminución exponencial de una población de hormigas"</span>) <span class="sc">+</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En la figura resultante, podemos observar cómo la biomasa disminuye exponencialmente a lo largo del tiempo, y cómo la línea horizontal roja nos indica el momento en que la biomasa alcanza los 93 gramos. El tiempo que tardará la biomasa en llegar a 93 gramos es de aproximadamente 12.39 años.</p>
<p><b style="color:#d95f02;"> Pregunta 4. Población de Peces </b></p>
<p><img src="https://images.pexels.com/photos/128756/pexels-photo-128756.jpeg?auto=compress&amp;cs=tinysrgb&amp;w=300" width="40%"></p>
<p>Una población de peces aumenta a una tasa anual de 7%. Si la población actual es de 8.000 individuos:</p>
<ol type="1">
<li><p>¿Cuántos años le tomará a esta población para llegar a 18.000 individuos?</p></li>
<li><p>Graficar la proyección de esta población en 20 periodos de tiempo.</p></li>
</ol>
<p><strong>R./</strong> Se requiere utilizar la fórmula para el crecimiento exponencial:</p>
<p><b style="color:#1f78b4;"> Nt = No * e^(r*t) </b></p>
<p><em>Ver los elementos de esta ecuación en el ejercicio inicial.</em></p>
<p>En este caso, se tiene que:</p>
<p><strong>No</strong>= 8000 indv.</p>
<p><strong>Nt</strong>= 18000 indv.</p>
<p><strong>t</strong>= ?</p>
<p><strong>r</strong>= -0.07 indv./indv.*t (aumento del 7%)</p>
<p><em>Preguntas a resolver:</em></p>
<ol type="1">
<li><p><strong>t</strong>= ?</p></li>
<li><p>Proyección exponencial en 20 periodos de tiempo</p></li>
</ol>
<p><em>Procedimiento</em></p>
<ol type="1">
<li>En este caso, si: <b style="color:#1f78b4;"> Nt = No * e^(r*t) </b>.</li>
</ol>
<p>De acuerdo a diferentes despejes logarítmicos:</p>
<p><b style="color:#1f78b4;"> t= [ln(Nt/No)]/[r * ln(e)] </b></p>
<p><strong>t</strong>= [ln(18000/8000)]/[0.07 * 1]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos la función para la disminución exponencial</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>Nt <span class="ot">&lt;-</span> <span class="cf">function</span>(No, r, t) {</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  No <span class="sc">*</span> <span class="fu">exp</span>(r <span class="sc">*</span> t)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>Nt</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function(No, r, t) {
  No * exp(r * t)
}</code></pre>
</div>
</div>
<ul>
<li>Cálculo del tamaño de la población en 7 periodos de tiempo <code>N7</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>t <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">log</span>(<span class="dv">18000</span><span class="sc">/</span><span class="dv">8000</span>)<span class="sc">/</span>(<span class="fl">0.07</span> <span class="sc">*</span> <span class="dv">1</span>), <span class="dv">2</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>t</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.58</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Figura de la proyección poblacional en 20 periodos de tiempo o 20 años.</li>
</ol>
<ul>
<li>Base de datos o data frame <code>datos</code>, en 20 periodos de tiempo, para posteriormente realizar la figura del modelo exponencial en ggplot</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos un data frame con los valores de población para varios tiempos</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">tiempo =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Nt =</span> <span class="fu">round</span>(<span class="fu">Nt</span>(<span class="at">No =</span> <span class="dv">8000</span>, <span class="at">r =</span> <span class="fl">0.07</span>, <span class="at">t =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>)))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  tiempo    Nt
1      0  8000
2      1  8580
3      2  9202
4      3  9869
5      4 10585
6      5 11353</code></pre>
</div>
</div>
<ul>
<li>Figura del modelo de proyección de la población en 20 periodos de tiempo.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafica de la evolución de la población</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> tiempo, <span class="at">y =</span> Nt)) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficamos la evolución de la población</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> tiempo, <span class="at">y =</span> Nt)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> t, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">x =</span> t <span class="sc">+</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="fu">max</span>(datos<span class="sc">$</span>Nt) <span class="sc">/</span> <span class="dv">2</span>, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"Aumento de Nt</span><span class="sc">\n</span><span class="st">en"</span>, t, <span class="st">"años"</span>),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Tiempo (años)"</span>) <span class="sc">+</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Población (Nt)"</span>) <span class="sc">+</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Crecimiento exponencial de la población de peces"</span>) <span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="modelos-de-crecimiento-logístico-1" class="level3">
<h3 class="anchored" data-anchor-id="modelos-de-crecimiento-logístico-1"><b style="color:#d95f02;"> Modelos de crecimiento logístico </b></h3>
<p><img src="https://t4.ftcdn.net/jpg/03/89/65/75/240_F_389657503_t0RWlHHRY5DExaXGWS2C0aIZBPZQSByB.jpg" width="40%"></p>
<p><b style="color:#d95f02;"> Pregunta 1. Población de mariposas </b></p>
<p><img src="https://t4.ftcdn.net/jpg/05/71/54/15/240_F_571541584_Y4idglBvC0TyTuKzpQWbSc0ZqfArRGA2.jpg" width="40%"></p>
<p>Suponga que una población de mariposas crece de acuerdo a la ecuación logística. Si la población inicia con 200 individuos y su capacidad de carga es de 500 mariposas y r= 0.1 ind/ind.més:</p>
<ol type="1">
<li><p>¿cuál es la tasa de crecimiento para la población?</p></li>
<li><p>Graficar la proyección de esta población en 10 periodos de tiempo.</p></li>
</ol>
<p><strong>R./</strong> Primero hay que utilizar la fórmula para el crecimiento lgístico de una población biológica:</p>
<p><b style="color:#1f78b4;"> dN/dt = r.No[1 - k/No] </b></p>
<p>A partir de la formula anterior se calcula el vaor de Nt:</p>
<p><b style="color:#1f78b4;"> Nt = K / [(1+((K/No)-1) * e^(-r.t))] </b></p>
<p><em>Donde</em>:</p>
<p><strong>Nt</strong>= densidad de la población después de un tiempo t</p>
<p><strong>No</strong>= densidad inicial de la población (en el tiempo 0)</p>
<p><strong>k</strong>= Capacidad de carga o límite de crecimiento de la población.</p>
<p><strong>r</strong>= tasa de crecimiento intrinsico o instantaneo.</p>
<p><strong>t</strong>= tiempo transcurrido (expresado en años)</p>
<p>En este caso, se tiene que:</p>
<p><strong>No</strong>= 200 individuos</p>
<p><strong>K</strong> = 500 individuos</p>
<p><strong>r</strong>= 0.1 indv./indv.*t (10% expresado como un decimal)</p>
<p><strong>Pregunta 1.</strong> Cálculo de la tasa de crecimiento logístico, de acuerdo a la siguiente ecuación:</p>
<p>dN/dt = rN(1-N/K)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 1: Definir los parámetros del modelo</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>No <span class="ot">&lt;-</span> <span class="dv">200</span>   <span class="co"># Población inicial</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">500</span>    <span class="co"># Capacidad de carga</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fl">0.1</span>    <span class="co"># Tasa de crecimiento</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 2: Calcular la tasa de crecimiento dN/dt</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>dN_dt <span class="ot">&lt;-</span> <span class="cf">function</span>(No) {</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  r <span class="sc">*</span> No <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> No<span class="sc">/</span>K)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>dN_dt</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function(No) {
  r * No * (1 - No/K)
}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tasa de crecimiento dN/dt con No= 200 truchas</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dN_dt</span>(<span class="dv">200</span>) <span class="co"># respuesta: 12 indv. / meses</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
<p>El paso 2 también se puede calcular así:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 2: Calcular la tasa de crecimiento dN/dt</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>dN_dt <span class="ot">&lt;-</span> r <span class="sc">*</span> No <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> No <span class="sc">/</span> K)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>dN_dt</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
<p><strong>Pregunta .</strong> Figura de proyección logística:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 1: Definir los parámetros del modelo</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>No <span class="ot">&lt;-</span> <span class="dv">200</span>   <span class="co"># Población inicial</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">500</span>    <span class="co"># Capacidad de carga</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fl">0.1</span>    <span class="co"># Tasa de crecimiento</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 2: Crear un vector de tiempo</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">60</span>, <span class="at">by =</span> <span class="dv">1</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 3: Calcular la población proyectada (Nt)</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>Nt <span class="ot">&lt;-</span> K <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> ((K<span class="sc">/</span>No) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>r<span class="sc">*</span>t))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 4: Crear un data frame con los resultados</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t =</span> t, <span class="at">Nt =</span> <span class="fu">round</span>(Nt,<span class="dv">0</span>))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  t  Nt
1 0 200
2 1 212
3 2 224
4 3 237
5 4 249
6 5 262</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 5: Graficar la población proyectada en función del tiempo</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> Nt)) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tiempo (meses)"</span>, <span class="at">y =</span> <span class="st">"Población de mariposas (Nt)"</span>) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Proyección de la población de mariposas"</span>) <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#d95f02;"> Pregunta 2. Población de truchas </b></p>
<p><img src="https://t3.ftcdn.net/jpg/05/80/37/42/240_F_580374263_AKgEYA3Ks7hzeTaGj9yTwtXtv936WbGq.jpg" width="40%"></p>
<p>Un biólogo pesquero quiere maximizar la producción de trucha manteniendo la población exactamente en Nt = 500 individuos (asume que este es el tamaño conducente a la máxima tasa de crecimiento poblacional entonces k = Nt y que su población crece en forma logística):</p>
<ol type="1">
<li><p>¿Prediga la tasa de crecimiento poblacional inicial al adicionar a la población 600 peces (No = 500 + 600) y explique su significado. Asuma que r para las truchas es de 0.005 individuos/individuo.día?</p></li>
<li><p>Graficar la relación y = dN/dt vs.&nbsp;x = Nt</p></li>
<li><p>Graficar la proyección de esta población en 80 periodos de tiempo.</p></li>
</ol>
<p><strong>R./</strong> Primero hay que utilizar la fórmula para el crecimiento lgístico de una población biológica:</p>
<p><b style="color:#1f78b4;"> dN/dt = r.No[1 - k/No] </b></p>
<p>A partir de la formula anterior se calcula el vaor de Nt:</p>
<p><b style="color:#1f78b4;"> Nt = K / [(1+((K/No)-1) * e^(-r.t))] </b></p>
<p><em>Donde</em>:</p>
<p><strong>Nt</strong>= densidad de la población después de un tiempo t</p>
<p><strong>K</strong>= capacidad de carga de la población</p>
<p><strong>No</strong>= densidad inicial de la población (en el tiempo 0)</p>
<p><strong>r</strong>= tasa de crecimiento intrinsico o instantaneo.</p>
<p><strong>t</strong>= tiempo transcurrido (expresado en días)</p>
<p>En este caso, se tiene que:</p>
<p><strong>Nt</strong>= 500 truchas</p>
<p><strong>K</strong>= 500 truchas</p>
<p><strong>No</strong>= 1100 truchas</p>
<p><strong>r</strong>= 0.05 indv./indv.*t (5%)</p>
<p><strong>Pregunta 1.</strong> Cálculo de la tasa de crecimiento poblacional inicial al adicionar a la población 600 peces (No = 500 + 600) y explique su significado, de acuerdo a la siguiente ecuación:</p>
<p>dN/dt = r.N.(1-N/K)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 1: Definir los parámetros</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>No <span class="ot">&lt;-</span> <span class="dv">1100</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fl">0.05</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso : Calcular la tasa de crecimiento poblacional inicial</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>dN_dt <span class="ot">&lt;-</span> r <span class="sc">*</span> No <span class="sc">*</span> ((K <span class="sc">-</span> No) <span class="sc">/</span> K)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>dN_dt  <span class="co"># Descenso de 66 individuos por día</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -66</code></pre>
</div>
</div>
<p><strong>Pregunta 2.</strong> Figura de relación t vs.&nbsp;dN_dt:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 1: Definir los parámetros del modelo</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>No <span class="ot">&lt;-</span> <span class="dv">200</span>   <span class="co"># Población inicial</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">500</span>    <span class="co"># Capacidad de carga</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fl">0.1</span>    <span class="co"># Tasa de crecimiento</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 2: Calcular la población proyectada (Nt)</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>dN_dt <span class="ot">&lt;-</span> r <span class="sc">*</span> No <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> No <span class="sc">/</span> K)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>dN_dt</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 2: Crear un vector de tiempo</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">999</span>, <span class="at">by =</span> <span class="dv">1</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 4: Crear un data frame con los resultados</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t=</span> t, <span class="at">Nt =</span> <span class="fu">seq</span>(<span class="dv">0</span>, K, <span class="at">length.out =</span> <span class="dv">1000</span>))</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  t        Nt
1 0 0.0000000
2 1 0.5005005
3 2 1.0010010
4 3 1.5015015
5 4 2.0020020
6 5 2.5025025</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Agregar columna dN_dt al dataframe (datos)</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span>dN_dt <span class="ot">&lt;-</span> r <span class="sc">*</span> datos<span class="sc">$</span>Nt <span class="sc">*</span> ((K <span class="sc">-</span> datos<span class="sc">$</span>Nt)<span class="sc">/</span>K)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  t        Nt      dN_dt
1 0 0.0000000 0.00000000
2 1 0.5005005 0.04999995
3 2 1.0010010 0.09989970
4 3 1.5015015 0.14969925
5 4 2.0020020 0.19939860
6 5 2.5025025 0.24899775</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 5: Graficar la tasa de crecimiento poblacional en función del tamaño de la población</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> Nt, <span class="at">y =</span> dN_dt)) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> K<span class="sc">/</span><span class="dv">2</span>, </span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> r <span class="sc">*</span> Nt <span class="sc">*</span> ((K <span class="sc">-</span> Nt)<span class="sc">/</span>K), </span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Población (Nt)"</span>, </span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Tasa de crecimiento poblacional (dN/dt)"</span>) <span class="sc">+</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Modelo logístico de crecimiento poblacional de la trucha"</span>) <span class="sc">+</span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Pregunta 3.</strong> Figura de proyección logística, mediante la función <code>sapply</code> así:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 1: Definir los parámetros del modelo</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>No <span class="ot">&lt;-</span> <span class="dv">1100</span>   <span class="co"># Población inicial</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">500</span>    <span class="co"># Capacidad de carga</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fl">0.05</span>    <span class="co"># Tasa de crecimiento</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 2: Crear un vector de tiempo</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">80</span>, <span class="at">by =</span> <span class="dv">1</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 3: Calcular la población proyectada (Nt)</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>Nt <span class="ot">&lt;-</span> <span class="fu">sapply</span>(t, <span class="cf">function</span>(t) K <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> ((K <span class="sc">/</span> No) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>r<span class="sc">*</span>t)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 4: Crear un data frame con los resultados</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t =</span> t, <span class="at">Nt =</span> <span class="fu">round</span>(Nt,<span class="dv">0</span>))</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos)  <span class="co"># 6 primeros datos del dataframe</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  t   Nt
1 0 1100
2 1 1039
3 2  987
4 3  942
5 4  903
6 5  869</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 5: Graficar la población proyectada en función del tiempo</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> Nt)) <span class="sc">+</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tiempo (meses)"</span>, <span class="at">y =</span> <span class="st">"Población de truchas (Nt)"</span>) <span class="sc">+</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Proyección de la población de truchas"</span>) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#d95f02;"> Pregunta 3. Población de tortugas </b></p>
<p><img src="https://t3.ftcdn.net/jpg/05/87/98/72/240_F_587987220_RlNmAT3LHkoGF3seQJomtPjd7FSDEY3V.jpg" width="40%"></p>
<p>Se estudia una población de tortugas denso-dependiente que tienen las siguientes relaciones para las tasas de nacimientos (b’) y mortalidad (d’) en función del tamaño poblacional (N):</p>
<p>b’= 0.10 + (0.03)N – (0.0005)N^2</p>
<p>d’ = 0.20 + (0.01)N:</p>
<ol type="1">
<li><p>Grafique estas funciones en el mismo gráfico y discuta la dinámica poblacional de la tortuga.</p></li>
<li><p>¿En qué difiere este modelo del modelo simple logístico con las funciones lineales de nacimientos y muertes?</p></li>
</ol>
<p><strong>R./</strong></p>
<p><strong>b’</strong>= tasas de nacimientos</p>
<p><strong>d’</strong>= tasas de muertes</p>
<p><strong>N</strong>= densidad de la población</p>
<p><strong>r</strong>= tasa de crecimiento intrinsico o instantaneo.</p>
<p><strong>Pregunta 1.</strong> Grafica de las funciones b’ y d’ de la dinámica poblacional de la tortuga.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 1: Definir función para calcular las tasas de crecimiento (b_d)</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>b_d <span class="ot">&lt;-</span> <span class="cf">function</span>(N) {</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  b <span class="ot">&lt;-</span> <span class="fl">0.10</span> <span class="sc">+</span> (<span class="fl">0.03</span><span class="sc">*</span>N) <span class="sc">-</span> (<span class="fl">0.0005</span><span class="sc">*</span>N<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> <span class="fl">0.20</span> <span class="sc">+</span> (<span class="fl">0.01</span><span class="sc">*</span>N)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> b <span class="sc">-</span> d</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(r)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>b_d</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function(N) {
  b &lt;- 0.10 + (0.03*N) - (0.0005*N^2)
  d &lt;- 0.20 + (0.01*N)
  r &lt;- b - d
  return(r)
}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 2: Crear vector de valores de N de 5 en 5 individuos hasta 80</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to=</span> <span class="dv">80</span>, <span class="at">by =</span> <span class="dv">5</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(N,<span class="dv">1</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 3: Tasas de nacimiento, mortalidad y crecimiento instantáneo para cada valor de N</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fl">0.10</span> <span class="sc">+</span> <span class="fl">0.03</span><span class="sc">*</span>N <span class="sc">-</span> <span class="fl">0.0005</span><span class="sc">*</span>N<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fl">0.20</span> <span class="sc">+</span> <span class="fl">0.01</span><span class="sc">*</span>N</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> b <span class="sc">-</span> d</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 4: Crear data frame con los datos</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">N =</span> N, <span class="at">b =</span> b, <span class="at">d =</span> d, <span class="at">r =</span> r)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">round</span>(datos,<span class="dv">2</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   N    b    d     r
1  0 0.10 0.20 -0.10
2  5 0.24 0.25 -0.01
3 10 0.35 0.30  0.05
4 15 0.44 0.35  0.09
5 20 0.50 0.40  0.10
6 25 0.54 0.45  0.09</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Paso 5: Crear gráfico</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> N)) <span class="sc">+</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y =</span> b, <span class="at">color =</span> <span class="st">"Nacimientos - b'"</span>)) <span class="sc">+</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y =</span> d, <span class="at">color =</span> <span class="st">"Muertes - d'"</span>)) <span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y =</span> r, <span class="at">color =</span> <span class="st">"Crecimiento - r"</span>)) <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">5.5</span>,<span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span>      <span class="co"># Intercepto en x</span></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">35</span>,<span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span>       <span class="co"># Intercepto en x</span></span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fl">5.5</span>, <span class="at">y =</span> <span class="fl">0.3</span>, <span class="at">label =</span> (<span class="st">"b = d"</span>)), </span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">size=</span> <span class="dv">3</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span>                        <span class="co"># Texto en el intercepto</span></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">35</span>, <span class="at">y =</span> <span class="fl">0.55</span>, <span class="at">label =</span> (<span class="st">"b = d"</span>)), </span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">size=</span> <span class="dv">3</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span>                      <span class="co"># Texto en el intercepto</span></span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fl">5.5</span>, <span class="at">y =</span> <span class="fl">0.26</span>), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">35</span>,  <span class="at">y =</span> <span class="fl">0.55</span>), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tamaño poblacional (N)"</span>, <span class="at">y =</span> <span class="st">"Tasas de crecimiento"</span>) <span class="sc">+</span></span>
<span id="cb70-19"><a href="#cb70-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Nacimientos - b'"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Muertes - d'"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"Crecimiento - r"</span> <span class="ot">=</span> <span class="st">"green"</span>)) <span class="sc">+</span> </span>
<span id="cb70-20"><a href="#cb70-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Taller6.poblaciones_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Podemos observar que la tasa de nacimientos (b’) disminuye a medida que la población(N) y las muertes (d’) aumenta. La tasa de crecimiento - r (b’ - d’), es positiva cuando la población es pequeña, pero se vuelve negativa cuando la población supera un cierto tamaño crítico (cuando b’ &gt; d’). Esto indica que la población de tortugas está limitada por su capacidad de carga.</p>
<p><strong>Pregunta 2.</strong> Diferencia del modelo anterior del modelo simple logístico con las funciones lineales de nacimientos y muertes.</p>
<p>El anterior modelo difiere del modelo simple logístico con las funciones lineales de nacimientos y muertes en que las tasas de nacimientos (b) y mortalidad (d) no son lineales, sino cuadráticas, presentando un máximo en b’ y r, luego una disminución a medida que la población aumenta.</p>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="cuestionario-para-resolver-en-casa" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="cuestionario-para-resolver-en-casa">Cuestionario para resolver en casa</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<section id="modelos-de-crecimiento-exponencial-2" class="level3">
<h3 class="anchored" data-anchor-id="modelos-de-crecimiento-exponencial-2"><b style="color:#d95f02;"> Modelos de crecimiento Exponencial </b></h3>
<ol type="1">
<li><p>Una población silvestre crece a una tasa anual del 7%. Si la población aumenta a 2000 en 7 años, ¿Cuál sería el tamaño de la población inicial?</p></li>
<li><p>Una población de curíes de interés para consumo, crece a una tasa anual del 3%. Si la población actual es de 3.000 individuos, ¿cuántos años se tardará para que doble su densidad?</p></li>
<li><p>Una población endémica de mariposas declina su densidad anual en 12,5%. A partir de una muestra de 127 gramos de biomasa, ¿cuál será su biomasa a los 6 años?</p></li>
<li><p>De acuerdo al artículo que titular “U.S. reaching the 300 million person milestone”, se destaca en unos de sus apartes, que la población de U.S. alcanzó 200 millones de personas en 1967. De acuerdo a lo anterior:</p></li>
</ol>
<ol type="a">
<li><p>Asumiendo que en 2007 la población alcanza los 303 millones (303.106), calcular la tasa de incremento instantáneo por año.</p></li>
<li><p>Si esta tendencia continúa por los 20 años siguientes, ¿cuál será el tamaño de la población en el año 2027?</p></li>
</ol>
<ol start="5" type="1">
<li><p>La proyección de naciones unidas para la población mundial, se da en un rango basado en diferentes escenarios posibles que pueden darse en el futuro. El menor estimador global para la población de 2050 es de 7.3 billones de personas y el mayor estimador es de 10.7 billones. ¿Cuál será la tasa de incremento anual en cada estimador, asumiendo que la población inicia con 6,6 billones en 2007? <a href="https://countrymeters.info/es/World">ENLACE</a></p></li>
<li><p>¿Cuánto tiempo puede tomar para que un par de individuos produzcan la población mundial actual (cerca de 10 billones de personas) con la presente tasa de crecimiento poblacional (r = 2,8% por año)? ¿En qué tiempo se doblaría esta población? Discuta el resultado.</p></li>
<li><p>En el momento en el que un libro de cabecera fue escrito se esperaba que la población humana mundial doblara en tamaño en aproximadamente 50 años. (a) calcule r para la población humana. Si la población en 1993 era de 5400 millones, (b) ¿cuál es el tamaño proyectado para el año 2010?</p></li>
<li><p>Usted estudia una población de escarabajos de tamaño 3.000. Durante el periodo de un mes usted registra 400 nacimientos y 150 muertes en esta población. (a) Estime r y (b) proyecte el tamaño poblacional en 6 meses.</p></li>
<li><p>Usted estudia una población de orquídeas en peligro para las cuales b= 0.0021 nacimientos/individuo.año y d= 0.0020 muertes/individuo.año. La población actual es de 40 plantas. Un nuevo centro comercial eliminará parte del hábitat de las orquídeas y reducirá la población a 20 plantas. Explique el efecto del desarrollo propuesto sobre la probabilidad de extinción de esta población.</p></li>
<li><p>Si una población de E. coli crece de 1000 células a 2x109 células en 6 h, ¿Cuál será su tasa intrínseca de incremento? ¿Está doblando su tiempo?</p></li>
</ol>
</section>
<section id="modelos-de-crecimiento-logístico-2" class="level3">
<h3 class="anchored" data-anchor-id="modelos-de-crecimiento-logístico-2"><b style="color:#d95f02;"> Modelos de crecimiento Logístico </b></h3>
<ol start="11" type="1">
<li><p>Una población de bacterias crece de acuerdo a la ecuación logística. Si la población inicial es de 500 bacterias y la capacidad de carga es de 10000 bacterias, y la tasa de crecimiento es de 0.05 bacterias/bacteria x hora, ¿cuál es la tasa de crecimiento para la población dN/dt?</p></li>
<li><p>Se tiene una población de plantas que crece de acuerdo a la ecuación logística. Si la población inicial es de 100 plantas y la capacidad de carga es de 400 plantas, y la tasa de crecimiento es de 0.02 plantas/planta x día, ¿cuántas plantas habrá después de 6 meses?</p></li>
<li><p>Una población de ratones crece de acuerdo a la ecuación logística. Si la población inicial es de 50 ratones y la capacidad de carga es de 500 ratones, y la tasa de crecimiento es de 0.1 ratones/ratón x semana, ¿en cuántas semanas la población alcanzará el 80% de su capacidad de carga?</p></li>
<li><p>Se investiga una población de aves denso-dependiente que tienen las siguientes relaciones para las tasas de nacimiento (b’) y mortalidad (d’) en función del tamaño poblacional (N): b’ = 0.12 + (0.01)N – (0.0001)N^2 d’ = 0.18 + (0.008)N ¿Cuál es el valor máximo que puede alcanzar la tasa de natalidad en esta población?</p></li>
<li><p>Se estudia una población de lagartos denso-dependiente que tienen las siguientes relaciones para las tasas de nacimiento (b’) y mortalidad (d’) en función del tamaño poblacional (N): b’ = 0.06 + (0.03)N – (0.0004)N^2 d’ = 0.21 + (0.007)N ¿Qué sucedería con la población si se redujera la tasa de mortalidad en un 50%? ¿Afectaría esto a la capacidad de carga de la población?</p></li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
</div> <!-- /content -->



</body></html>